export const COUNT = 'COUNT'
export const LIST = 'LIST'
export const CAR_INFO = 'CAR_INFO'
export const GET_CAR_FILE = 'GET_CAR_FILE'
export const IS_LOAD = 'IS_LOAD'
export const GET_PASPORT = 'GET_PASPORT'
export const GET_PASPORT_DETAIL = 'GET_PASPORT_DETAIL'
export const SET_PASPORT_ITEM = 'SET_PASPORT_ITEM'